export const RULE_REQUEST = "RULE_REQUEST";
export const RULE_SUCCESS = "RULE_SUCCESS";

export const QUOTE_REQUEST = "QUOTE_REQUEST";
export const QUOTE_SUCCESS = "QUOTE_SUCCESS";

export const RETURN_QUOTE_REQUEST = "RETURN_QUOTE_REQUEST";
export const RETURN_QUOTE_SUCCESS = "RETURN_QUOTE_SUCCESS";
